Set-StrictMode -Version Latest

function Test-OpenNVLauncherOwnedConfig {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string]$Generator
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return $false
    }

    $expectedHeader = "# Generated by $Generator."
    # ReadLines is lazy and Select-Object -First can retain its file handle in
    # this PowerShell process. Read the small generated configuration eagerly
    # so a following safe migration can replace the same file.
    $firstLine = ([IO.File]::ReadAllText($Path) -split "`r?`n", 2)[0]
    return [string]$firstLine -ceq $expectedHeader
}

function Save-OpenNVLauncherConfigBackup {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string]$Description,
        [switch]$PreviewOnly
    )

    $hash = (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant().Substring(0, 16)
    $profileRoot = Split-Path -Parent $Path
    $backupRoot = Join-Path $profileRoot "launcher-config-backups"
    $backupName = "$(Split-Path -Leaf $Path).$hash.bak"
    $backupPath = Join-Path $backupRoot $backupName
    if (Test-Path -LiteralPath $backupPath -PathType Leaf) {
        return $backupPath
    }

    if ($PreviewOnly) {
        Write-Host "Would preserve previous $Description at $backupPath"
        return $backupPath
    }

    New-Item -ItemType Directory -Path $backupRoot -Force | Out-Null
    Copy-Item -LiteralPath $Path -Destination $backupPath -ErrorAction Stop
    return $backupPath
}

function Get-OpenNVConfigPathSetting {
    param(
        [Parameter(Mandatory=$true)][string]$Text,
        [Parameter(Mandatory=$true)][string]$Key,
        [Parameter(Mandatory=$true)][string]$ConfigPath
    )

    $value = ""
    foreach ($line in @($Text -split "`r?`n")) {
        if ($line -match ("^" + [regex]::Escape($Key) + "=(.*)$")) {
            $value = [string]$Matches[1]
        }
    }
    if ([string]::IsNullOrWhiteSpace($value)) {
        return ""
    }
    if (-not [IO.Path]::IsPathRooted($value)) {
        $value = Join-Path (Split-Path -Parent $ConfigPath) $value
    }
    return [IO.Path]::GetFullPath($value)
}

function Copy-OpenNVLauncherSaves {
    param(
        [Parameter(Mandatory=$true)][string]$CurrentText,
        [Parameter(Mandatory=$true)][string]$ExpectedText,
        [Parameter(Mandatory=$true)][string]$ConfigPath,
        [switch]$PreviewOnly
    )

    $previousUserdata = Get-OpenNVConfigPathSetting -Text $CurrentText -Key "user-data" -ConfigPath $ConfigPath
    $nextUserdata = Get-OpenNVConfigPathSetting -Text $ExpectedText -Key "user-data" -ConfigPath $ConfigPath
    if ([string]::IsNullOrWhiteSpace($previousUserdata) -or [string]::IsNullOrWhiteSpace($nextUserdata) -or
        $previousUserdata.Equals($nextUserdata, [StringComparison]::OrdinalIgnoreCase)) {
        return [pscustomobject]@{ copied = 0; source = $previousUserdata; destination = $nextUserdata }
    }

    $previousSaves = Join-Path $previousUserdata "saves"
    if (-not (Test-Path -LiteralPath $previousSaves -PathType Container)) {
        return [pscustomobject]@{ copied = 0; source = $previousUserdata; destination = $nextUserdata }
    }

    $previousSavesFull = [IO.Path]::GetFullPath($previousSaves).TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
    $nextSaves = Join-Path $nextUserdata "saves"
    $candidates = [Collections.Generic.List[object]]::new()
    $conflicts = [Collections.Generic.List[string]]::new()
    foreach ($source in @(Get-ChildItem -LiteralPath $previousSavesFull -Recurse -File)) {
        $relative = $source.FullName.Substring($previousSavesFull.Length).TrimStart([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
        $destination = Join-Path $nextSaves $relative
        if (Test-Path -LiteralPath $destination -PathType Leaf) {
            $sourceHash = (Get-FileHash -LiteralPath $source.FullName -Algorithm SHA256).Hash
            $destinationHash = (Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash
            if ($sourceHash -cne $destinationHash) {
                $conflicts.Add("$relative already exists with different contents")
            }
            continue
        }
        $candidates.Add([pscustomobject]@{ source = $source.FullName; destination = $destination })
    }
    if ($conflicts.Count -gt 0) {
        throw "Cannot migrate existing launcher saves into the shared campaign store without overwriting data: $($conflicts -join '; '). Keep the current profile configuration or resolve the named save conflict first."
    }

    if ($PreviewOnly) {
        if ($candidates.Count -gt 0) {
            Write-Host "Would preserve $($candidates.Count) existing save file(s) from $previousUserdata into $nextUserdata"
        }
        return [pscustomobject]@{ copied = 0; source = $previousUserdata; destination = $nextUserdata }
    }

    foreach ($candidate in $candidates) {
        New-Item -ItemType Directory -Path (Split-Path -Parent $candidate.destination) -Force | Out-Null
        Copy-Item -LiteralPath $candidate.source -Destination $candidate.destination -ErrorAction Stop
    }
    if ($candidates.Count -gt 0) {
        Write-Host "Preserved $($candidates.Count) existing save file(s) in the shared campaign store; original files remain at $previousUserdata"
    }
    return [pscustomobject]@{ copied = $candidates.Count; source = $previousUserdata; destination = $nextUserdata }
}

function Write-OpenNVLauncherConfig {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string]$Text,
        [Parameter(Mandatory=$true)][string]$Description,
        [Parameter(Mandatory=$true)][string]$Generator,
        [switch]$AllowReplace,
        [switch]$AllowGeneratedUpgrade,
        [switch]$PreviewOnly
    )

    $backupPath = ""
    if (Test-Path -LiteralPath $Path -PathType Leaf) {
        $current = [IO.File]::ReadAllText($Path) -replace "`r`n", "`n"
        $expected = $Text -replace "`r`n", "`n"
        if ($current -ceq $expected) {
            return "unchanged"
        }

        $launcherOwned = Test-OpenNVLauncherOwnedConfig -Path $Path -Generator $Generator
        if (-not $AllowReplace -and -not ($AllowGeneratedUpgrade -and $launcherOwned)) {
            throw "Existing $Description differs from the generated OpenNV profile. Refusing to overwrite $Path; pass -Force only if this profile is disposable."
        }
        $backupPath = Save-OpenNVLauncherConfigBackup -Path $Path -Description $Description -PreviewOnly:$PreviewOnly
        Copy-OpenNVLauncherSaves -CurrentText $current -ExpectedText $expected -ConfigPath $Path -PreviewOnly:$PreviewOnly | Out-Null
    }

    if ($PreviewOnly) {
        Write-Host "Would write ${Description}: $Path"
        return "preview"
    }

    [IO.File]::WriteAllText($Path, $Text, [Text.UTF8Encoding]::new($false))
    if (-not [string]::IsNullOrWhiteSpace($backupPath)) {
        Write-Host "Updated launcher-owned $Description; preserved the previous generated config at $backupPath"
    }
    return "written"
}

function Get-OpenNVLauncherConfigState {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string]$Text,
        [Parameter(Mandatory=$true)][string]$Generator
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        return "missing"
    }

    $current = [IO.File]::ReadAllText($Path) -replace "`r`n", "`n"
    $expected = $Text -replace "`r`n", "`n"
    if ($current -ceq $expected) {
        return "current"
    }
    if (Test-OpenNVLauncherOwnedConfig -Path $Path -Generator $Generator) {
        return "managed-upgrade-required"
    }
    return "custom-configuration"
}
